### ISSUE TITLE
Plugin generates app.yaml with env: string

### ISSUE THREAD

**Issue by Spark2Ignite** [GoogleCloudPlatform/gcloud-maven-plugin#61]
When running mvn gcloud:deploy, it generates app.yaml as following:

```
runtime: java
env: 2
api_version: 1
threadsafe: True
handlers:
  - url: .*
    script: dynamic
```

The problem with ```env: 2``` line is that triggers ManagedVM style deployment and not regular (classic) AppEngine deployment.

Is there is any way to generate app.yaml without  ```env: 2``` ?
